### PR TITLE
Variables renamed, documentation fixed

### PR DESCRIPTION
**Pull request by rdkt-wro**
Hi! I use your library at work and I have found a minor naming issue. Thanks, Radek

### CODE REVIEW

**Comment by akamsteeg** [comment]
Thanks for your contribution! I'll review this as soon as possible. :)

**Comment by sqet** [comment]
@akamsteeg What about reviewing this? :)

**Comment by akamsteeg** [comment]
Sorry for the delay, this completely slipped my mind (for over a year...). Thanks for your contribution @rdkt-wro!

**Comment by rdkt-wro** [comment]
You're welcome @akamsteeg :)

**Pull request merged**
